sudo: required
services:
  - docker

before_install:
  - docker build -t Gallagher94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run Gallagher94/react-test npm test -- -- coverage

after_success:
  - docker build -t Gallagher94/multi-client ./client
  - docker build -t Gallagher94/multi-nginx  ./nginx
  - docker build -t Gallagher94/multi-server ./server
  - docker build -t Gallagher94/multi-worker ./worker

# Login and push images to docker hub

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
 - docker push Gallagher94/multi-client 
 - docker push Gallagher94/multi-nginx
 - docker push Gallagher94/multi-server 
 - docker push Gallagher94/multi-worker